baseURL = "https://oddconley.com/"
languageCode = "en-us"
title = "odd Conley"
theme = "PaperMod"

[params]
  author = "odd Conley"
  description = "Weird fiction. Open worlds."
  defaultTheme = "dark"

[params.profileMode]
  enabled = true
  title = "odd Conley"
  subtitle = "Weird fiction. Open worlds."

[[params.profileMode.buttons]]
  name = "The Book"
  url = "/book/"

[[params.profileMode.buttons]]
  name = "Get Updates"
  url = "/newsletter/"

[[menus.main]]
name = "The Book"
url = "/book/"
weight = 1

[[menus.main]]
name = "Newsletter"
url = "/newsletter/"
weight = 2

[[menus.main]]
name = "Using This World"
url = "/license/"
weight = 3

[[menus.main]]
name = "About"
url = "/about/"
weight = 4

[[menus.main]]
name = "Kittens"
url = "/kittens/"
weight = 5
